name: askida
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.4.10
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1
  image: ^4.3.0
  firebase_app_check: ^0.3.2+10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
