// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqmbY38YXJqkO8cSUk4FUmEe2aHMMVGn8',
    appId: '1:907566503666:android:a5b6c7d8e9f0a1b2a8e26b',
    messagingSenderId: '907566503666',
    projectId: 'askida788',
    storageBucket: 'askida788.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCFSuUJNZldMjXc5HLB_xxjOaZaIql5iQ',
    appId: '1:907566503666:web:c3386729d6dbae6ca8e26b',
    messagingSenderId: '907566503666',
    projectId: 'askida788',
    authDomain: 'askida788.firebaseapp.com',
    storageBucket: 'askida788.firebasestorage.app',
    measurementId: 'G-F2XK5L1SXS',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqmbY38YXJqkO8cSUk4FUmEe2aHMMVGn8',
    appId: '1:907566503666:ios:93f0e9c728dadaf5a8e26b',
    messagingSenderId: '907566503666',
    projectId: 'askida788',
    storageBucket: 'askida788.firebasestorage.app',
    iosBundleId: 'com.example.askida',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqmbY38YXJqkO8cSUk4FUmEe2aHMMVGn8',
    appId: '1:907566503666:ios:93f0e9c728dadaf5a8e26b',
    messagingSenderId: '907566503666',
    projectId: 'askida788',
    storageBucket: 'askida788.firebasestorage.app',
    iosBundleId: 'com.example.askida',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCFSuUJNZldMjXc5HLB_xxjOaZaIql5iQ',
    appId: '1:907566503666:web:2362b846b108c3c5a8e26b',
    messagingSenderId: '907566503666',
    projectId: 'askida788',
    authDomain: 'askida788.firebaseapp.com',
    storageBucket: 'askida788.firebasestorage.app',
    measurementId: 'G-0Z9FBX2NGY',
  );
}



